name: ladlani_ss
description: تطبيق LadlaniSS لإدارة الحراسة الفصلية.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  supabase_flutter: ^1.10.21
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  pdf: ^3.10.4
  excel: ^3.0.0
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/lang/ar.json
    - assets/lang/fr.json
