name: ladlaniss
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.20
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  file_picker: ^6.1.1
  excel: ^4.0.2
  path_provider: ^2.1.3
  pdf: ^3.10.8
  printing: ^5.12.0
  flutter_local_notifications: ^17.1.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
